apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-hub.argocd.0.0.2
  annotations:
    argo-hub/version: '0.0.2'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argo-hub.argocd.0.0.2
  annotations:
    argo-hub/version: '0.0.2'
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - watch
      - patch
  - apiGroups:
      - ""
    resources:
      - pods/log
    verbs:
      - get
      - watch
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-hub.argocd.0.0.2
  annotations:
    argo-hub/version: '0.0.2'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argo-hub.argocd.0.0.2
subjects:
  - kind: ServiceAccount
    name: argo-hub.argocd.0.0.2
