apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-hub.codefresh-csdp.0.0.7
  annotations:
    argo-hub/version: '0.0.7'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argo-hub.codefresh-csdp.0.0.7
  annotations:
    argo-hub/version: '0.0.7'
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - watch
      - patch
  - apiGroups:
      - ""
    resources:
      - pods/log
    verbs:
      - get
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-hub.codefresh-csdp.0.0.7
  annotations:
    argo-hub/version: '0.0.7'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argo-hub.codefresh-csdp.0.0.7
subjects:
  - kind: ServiceAccount
    name: argo-hub.codefresh-csdp.0.0.7
