apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: argo-hub.jira
  annotations:
    argo-hub/description: 'Execute operations against Jira'
    argo-hub/categories: 'task management'
    argo-hub/icon_url: "https://cdn.jsdelivr.net/gh/codefresh-io/argo-hub@main/coming-soon/jira/icon.svg"
    argo-hub/icon_background: "#f4f4f4"
spec:
  templates: []
