apiVersion: v1
kind: ServiceAccount
metadata:
  name: codefresh-marketplace.github.0.0.1
  annotations:
    codefresh-marketplace/version: '0.0.1'
    eks.amazonaws.com/role-arn: arn:aws:iam::559963890471:role/argo-worklfows-s3-artifact-repo
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: codefresh-marketplace.github.0.0.1
  annotations:
    codefresh-marketplace/version: '0.0.1'
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - watch
      - patch
  - apiGroups:
      - ""
    resources:
      - pods/log
    verbs:
      - get
      - watch
  - apiGroups:
      - ""
    resources:
      - pods/exec
    verbs:
      - create
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - create
      - get
      - update
  - apiGroups:
      - argoproj.io
    resources:
      - workflows
      - workflowtemplates
    verbs:
      - create
      - delete
      - list
      - get
      - watch
      - update
      - patch
  - apiGroups:
      - argoproj.io
    resources:
      - workflowtasksets
      - workflowtasksets/finalizers
    verbs:
      - list
      - watch
      - get
      - update
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: codefresh-marketplace.github.0.0.1
  annotations:
    codefresh-marketplace/version: '0.0.1'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: codefresh-marketplace.github.0.0.1
subjects:
  - kind: ServiceAccount
    name: codefresh-marketplace.github.0.0.1

