apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: argo-hub.starting-template.0.0.1
  annotations:
    argo-hub/version: '0.0.1'
    argo-hub/description: 'Starting template'
    argo-hub/categories: 'argo'
    argo-hub/license: 'MIT'
    argo-hub/owner_name: 'Itai Gendler'
    argo-hub/owner_email: 'itai@codefresh.io'
    argo-hub/owner_avatar: 'https://avatars.githubusercontent.com/u/10414627?s=120&v=4'
    argo-hub/owner_url: 'https://github.com/itai-codefresh'
    argo-hub/icon_url: "https://cdn.jsdelivr.net/gh/codefresh-io/argo-hub@main/workflows/starting-template/assets/icon.svg"
    icon-background: "#81D4FA"
spec:
  templates:
    - name: task
      serviceAccountName: argo-hub.starting-template.0.0.1
      metadata:
        annotations:
          argo-hub-template/description: 'task'
          argo-hub-template/icon_url: "https://cdn.jsdelivr.net/gh/codefresh-io/argo-hub@main/workflows/starting-template/assets/icon.svg"
          argo-hub-template/icon_background: "#f4f4f4"
      inputs:
        parameters:
          - name: TEXT
      container:
        name: main
        imagePullPolicy: Always
        image: alpine
        command:
          - echo {{ inputs.parameters.TEXT }}
