apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: codefresh.terminate-workflow
  labels:
    icon-type: svg
    icon-url: https://cdn.jsdelivr.net/gh/codefresh-io/steps/graduated/build/icon-2.svg
    icon-background: "#81D4FA"
spec:
  templates:
    - name: main
      inputs:
        parameters:
          - name: NAME
            default: ''
          - name: LABEL_SELECTOR
            default: ''
          - name: FIELD_SELECTOR
            default: ''
      container:
        name: main
        imagePullPolicy: Always
        image: argoproj/argocli
        command:
          - argo
          - terminate
          - '{{ inputs.parameters.NAME }}'
          - --selector
          - "{{ inputs.parameters.LABEL_SELECTOR }},workflows.argoproj.io/phase=Running"
          - --field-selector
          - "{{ inputs.parameters.FIELD_SELECTOR }}"
